export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_LIVES = 'UPDATE_LIVES';
export const UPDATE_POKEMON = 'UPDATE_POKEMON';
export const UPDATE_PLAYER_FOUNDS = 'UPDATE_PLAYER_FOUNDS';
