export const UPDATE_THEME_SELECTION = 'UPDATE_THEME_SELECTION';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_CURRENT_POKEMON = 'UPDATE_CURRENT_POKEMON';
export const UPDATE_POKEMON_NAMES = 'UPDATE_POKEMON_NAMES';
