export const UPDATE_THEME_SELECTION = 'UPDATE_THEME_SELECTION';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_POKEMON_NAMES = 'UPDATE_POKEMON_NAMES';
export const UPDATE_POKEMON = 'UPDATE_POKEMON';
